### PR TITLE
.

### PR DESCRIPTION
**Pull request by sowmya-kota07**

### CODE REVIEW

**Review by hbuchel — COMMENTED** [review]
Hi @sowmyadev-kota! Thanks for opening this! In your PR, you've updated the snapshot file, but what really needs to be updated is the file where we define our type for inert and the description for it. [types/base.ts](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/src/primitives/types/base.ts) should be the right file.

After that, you can run `yarn docs test -u` This will then update the snapshot file based on your change.

Also a small nit, previously we didn't do a good job naming these links which results in a bunch of duplicate links labeled "MDN" which isn't great for accessibility. Can we make the link text say "Inert on MDN"?

**Comment by sowmyadev-kota** [comment]
@hbuchel , sorry I didn't get a chance to test this, will make the update, thank you

**Comment by calebpollman** [comment]
@sowmyadev-kota Is this PR still active?

**Comment by calebpollman** [comment]
@sowmyadev-kota Going to close this for now but please re-open if still relevant

**Pull request closed without merging**
