### PR TITLE
chore(aws-amplify): expand range of amplify peerDeps

### PR DESCRIPTION
**Pull request by calebpollman**
#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are updated
- [ ] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by dbanksdesign — APPROVED** [review]
LGTM!

**Review by thaddmt — DISMISSED** [review]

**Review by elorzafe — DISMISSED** [review]
Looks good to me

Thanks @calebpollman 🌮

**Review by wlee221 — APPROVED** [review]

**Review by dbanksdesign — APPROVED** [review]
LGTM! :shipit:

**Comment by calebpollman** [comment]
CI passed [here](https://github.com/aws-amplify/amplify-ui/runs/9424758682), only added a changeset

**Pull request merged**
