### PR TITLE
fix: remove docs legacy ui-react dep

### PR DESCRIPTION
**Pull request by reesscot**
*Description of changes:*
This fixes an issue in yarn.lock where the `ui-react-v1` was oddly pointing to v2.  ~This is fixed by pinning to the same legacy version we use in the [react/package.json](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/package.json#L53).~ 

*Update*
Digging a bit more I realized that the ui-react-legacy depency is not being used anywhere in the docs, and would be available through the `ui-react` dependency if needed in the future, so I'm removing it from the docs dependencies. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by joebuono — APPROVED** [review]
Good catch!

**Review by ErikCH — APPROVED** [review]
Looks good. That should pin it correctly

**Review by zchenwei — APPROVED** [review]
LGTM!

**Comment by wlee221** [comment]
@reesscot Ah I know exactly what this error is! I found this while working with @calebpollman on setting up his ui environment. 

It's related to latest version of Cypress + cucumber. Can you look to apply the fix documented here? https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/658

**Pull request merged**
