### PR TITLE
docs: Update card link title style

### PR DESCRIPTION
**Pull request by ioanabrooks**
#### Description of changes

Adds an animation on mouse over of the card link title in docs.

Kapture 2022-07-22 at 10 58 17

#### Issue #, if available

N/A

#### Description of how you validated changes

Ran docs locally.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are updated
- [ ] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by joebuono — APPROVED** [review]
Cool. LGTM!

Also remember to add a changeset

**Review by 0618 — APPROVED** [review]
Fancy! I like it ❤️

**Review by zchenwei — APPROVED** [review]
nice!

**Comment by reesscot** [comment]
So cool @ioanabrooks!

**Pull request merged**
