### PR TITLE
Flutter Docs - fixed signIn method case

### PR DESCRIPTION
**Pull request by malaquf**
#### Description of changes

Fixed documentation to match actual ButtonResolver method signature:
```
  String signIn(BuildContext context) {
    return AuthenticatorLocalizations.buttonsOf(context).signIn;
  }
```

#### Checklist

- [x] Have read the [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md)
- [x] PR description included
- [x] Relevant documentation is changed or added (and PR referenced)
- [x] `yarn test` passes and tests are updated/added
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by Equartey — APPROVED** [review]
Good catch!

**Review by isaaccarrington — APPROVED** [review]
Looks good to me

**Review by reesscot — APPROVED** [review]

**Review by reesscot — APPROVED** [review]
LGTM

**Comment by calebpollman** [comment]
Admin merged, PR only touches docs

**Pull request merged**
