### PR TITLE
fix:(file-uploader): Swap Save and Cancel Button

### PR DESCRIPTION
**Pull request by ErikCH**
#### Description of changes

To adhere to best practices, we are swapping the placement of the save and cancel buttons when editing a file.

Before
Screen Shot 2023-01-25 at 10 34 32 AM

After
Screen Shot 2023-01-25 at 10 37 33 AM

#### Description of how you validated changes
We have extensive tests that test edit and save.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are updated
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ioanabrooks — CHANGES_REQUESTED** [review]
I think the mainstream is not yet settled on whether having the primary button action be last is the best practice, but if we are going to be opinionated on this we should be consistent and also change the position of the edit/remove actions [screenshot below]. Did we consider accessibility? If using keyboard only does reaching the primary action require an extra key press now?

Screen Shot 2023-01-25 at 11 26 42 AM

**Comment by dbanksdesign** [comment]
This was brought up in the fit-n-finish review with the design org. TBH its not a big deal to me either way. @hbuchel do you have any thoughts on this from an accessibility point of view?

**Comment by ErikCH** [comment]
> I think the mainstream is not yet settled on whether having the primary button action be last is the best practice, but if we are going to be opinionated on this we should be consistent and also change the position of the edit/remove actions [screenshot below]. Did we consider accessibility? If using keyboard only does reaching the primary action require an extra key press now?
> 
> Screen Shot 2023-01-25 at 11 26 42 AM

OK! In a separate PR I'll move the edit button so we don't have any inconsistencies. As for keyboard users they can either hit enter on the input to save, or it's two tab presses to get to save.

**Review by dbanksdesign — APPROVED** [review]

**Review by ioanabrooks — DISMISSED** [review]

**Review by ioanabrooks — APPROVED** [review]
LGTM

**Pull request merged**
