### PR TITLE
chore(bump map libre)

### PR DESCRIPTION
**Pull request by ErikCH**
#### Description of changes
Update map libre to latest

Based on this security [fix](https://github.com/maplibre/maplibre-gl-js/pull/1135)

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are updated
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by calebpollman — APPROVED** [review]
LGTM 🚢

**Review by wlee221 — COMMENTED** [review]
Good catch!

**Review by wlee221 — APPROVED** [review]

**Review by 0618 — APPROVED** [review]

**Review by reesscot — APPROVED** [review]

**Comment by 0618** [comment]
Thanks DependEric!

**Review by slaymance — COMMENTED** [review]
Should this change also be reflected in our `yarn.lock`?

**Review by zchenwei — APPROVED** [review]
You are ahead of dependabot!

**Comment by ErikCH** [comment]
> Should this change also be reflected in our `yarn.lock`?

Thanks! Yup added.

**Review by slaymance — APPROVED** [review]
:ship:

**Pull request merged**
