### PR TITLE
[DO NOT MERGE YET] Remove icons

### PR DESCRIPTION
**Pull request by dbanksdesign**
#### Description of changes

Removing built-in icons (except the ones other components need) to reduce the blot of the UI package. Updated the docs to reflect these changes. 

#### Issue #, if available

#1101

#### Description of how you validated changes

Built and viewed docs site. 

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are updated
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ayush987goyal** [comment]
@dbanksdesign Thanks a ton for this PR!

Could you also keep the following icons as they are used in the staging repo?

1. IconClose
2. IconCheckCircleOutline
3. IconHighlightOff
4. IconFiberManualRecord

Thanks!

**Comment by dbanksdesign** [comment]
@ayush987goyal will do!

**Review by joebuono — APPROVED** [review]
LGTM!

**Review by zchenwei — APPROVED** [review]
LGTM! :shipit: I changed the base to `3.0`, which was created for the next major release.

**Review by reesscot — APPROVED** [review]
LGTM

**Pull request merged**
