### PR TITLE
chore: move internal studio utils to separate file

### PR DESCRIPTION
**Pull request by reesscot**
#### Description of changes
This PR moves the util functions exported to support code generation by Amplify Studio UI Builder to a separate file for better separation of concerns.

#### Description of how you validated changes
All the studio exports are still being exported:
```
          "findChildOverrides",
          "getOverrideProps",
          "getOverridesFromVariants",
          "mergeVariantsAndOverrides",
```

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are updated
- [x ] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by Jshhhh — APPROVED** [review]
LGTM

**Review by ioanabrooks — DISMISSED** [review]

**Review by calebpollman — COMMENTED** [review]
Since these utils (from what i can tell) don't depend on anything in the _primitives_ directory what do you think of moving these them of to their own _studio_ directory?

**Review by hein-j — APPROVED** [review]

**Review by zchenwei — APPROVED** [review]
LGTM

**Review by slaymance — COMMENTED** [review]
This looks good. I like @calebpollman's suggestion to move internal Studio functionality to its own directory and maybe even start thinking about breaking these out of the UI repo entirely.

**Comment by reesscot** [comment]
@slaymance @calebpollman Updated the PR to move the studio code into a separate folder and split each function into a separate file and test file. This should make it easier to maintain going forward.

**Review by hein-j — APPROVED** [review]

**Review by Jshhhh — APPROVED** [review]
LGTM

**Review by calebpollman — DISMISSED** [review]
LGTM, thanks for the updates and breaking out the utils in to their own files. One request, can we add `'src/studio'` to the `files` array on line 66 of _.eslintrc.js_ to retain linting on the new directory?

**Review by ioanabrooks — DISMISSED** [review]
LGTM

**Review by ioanabrooks — APPROVED** [review]

**Review by calebpollman — APPROVED** [review]
🚢

**Review by zchenwei — APPROVED** [review]

**Pull request merged**
