### PR TITLE
Adding export dist/styles.css to fix missing export error. See issue …

### PR DESCRIPTION
**Pull request by SilverLinings89**
Addresses issue 2999. Someone with more understanding of what this export is used for may be able to device a better solution, but this fixes import bugs in angular 15 and seems to be a solid fix.

#### Description of changes

The added line adds an additional export of a file that is already being exported under a different name. In some cases, however, the requested name includes ./dist, which leads to an error. 

#### Issue #, if available

issues 2999: https://github.com/aws-amplify/amplify-ui/issues/2999

#### Description of how you validated changes

The changes were not validated because simply adding another label to an already existing export should not have any other impact.

#### Checklist

- [x] PR description included
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by wlee221** [comment]
Hi! Took a look at this issue, I think it might be better to change `angular` package instead of `ui` package, so that other framework packages aren't affected. I'll open a PR soon!

**Review by 0618 — APPROVED** [review]

**Review by joebuono — APPROVED** [review]
Thank you!

**Comment by 0618** [comment]
Thanks for contributing! ❤️

**Review by wlee221 — APPROVED** [review]
Appreciate your contribution @SilverLinings89!

**Review by joebuono — APPROVED** [review]

**Review by 0618 — APPROVED** [review]

**Pull request merged**
