### PR TITLE
BREAKING CHANGE(react): bump minimum React version to 16.14.0

### PR DESCRIPTION
**Pull request by zchenwei**
#### Description of changes

1. Bump the minimum React version that gets supported in `@aws-amplify/ui-react` to `16.14.0`. This is a safe since we do not update `types/react` and so we no longer promise to support an old React version.

2. With React `16.14.0`, we can now use the new JSX transform to transpile code.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are updated
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by dbanksdesign — DISMISSED** [review]

**Comment by calebpollman** [comment]
Have we tested this against `@aws-amplify/ui-react-native`?

**Comment by zchenwei** [comment]
> Have we tested this against `@aws-amplify/ui-react-native`?

Not yet. Do we have a flow about how to test against `ui-react-native`? I can kick off a test with that

**Comment by calebpollman** [comment]
> > Have we tested this against `@aws-amplify/ui-react-native`?
> 
> Not yet. Do we have a flow about how to test against `ui-react-native`? I can kick off a test with that

Needs to be manually tested unfortunately

**Comment by zchenwei** [comment]
> > > Have we tested this against `@aws-amplify/ui-react-native`?
> > 
> > 
> > Not yet. Do we have a flow about how to test against `ui-react-native`? I can kick off a test with that
> 
> Needs to be manually tested unfortunately

Ok so I pull down the `rna/main` branch and test out the changes manually. We may also want to bring up `react` peer dependency to `16.14.0` in that branch as well

**Comment by calebpollman** [comment]
> > > > Have we tested this against `@aws-amplify/ui-react-native`?
> > > 
> > > 
> > > Not yet. Do we have a flow about how to test against `ui-react-native`? I can kick off a test with that
> > 
> > 
> > Needs to be manually tested unfortunately
> 
> Ok so I pull down the `rna/main` branch and test out the changes manually. We may also want to bring up `react` peer dependency to `16.14.0` in that branch as well

So i think i may have confused you here, we need to test against `@aws-amplify/ui-react-native` in `next-release/main`. We have the In-App Messaging components (and the first release of `@aws-amplify/ui-react-native`) on  `next-release/main`

**Review by Milan-Shah — APPROVED** [review]

**Review by calebpollman — APPROVED** [review]

**Review by wlee221 — APPROVED** [review]

**Pull request merged**
