### PR TITLE
Confirm Sign Up tests

### PR DESCRIPTION
**Pull request by ericclemmons**
*Issue #, if available:* Fixes https://github.com/aws-amplify/amplify-ui/issues/569

> Screen Shot 2021-11-01 at 2 52 25 PM

*Description of changes:*

- [x] Update `confirm-sign-up.feature` tests to run against `@angular @react @vue`
- [x] Introduce new `I mock {string} with fixture {string}` behavior
- [x] Expose `window.Amplify.*` for the new behavior 
- [x] Fix React tests (@ericclemmons)
- [x] Fix Vue tests (@ErikCH)
- [x] Fix Angualr tests (@wlee221)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by ericclemmons — COMMENTED** [review]
@ErikCH I've made a small change for Vue, but I'm noticing that Cypress is having issues typing into the `Confirmation Code` field.  Can you help debug these?
Screen Shot 2021-11-02 at 1 37 54 PM
Screen Shot 2021-11-02 at 1 38 06 PM
Screen Shot 2021-11-02 at 1 38 29 PM

**Review by ericclemmons — COMMENTED** [review]
@wlee221 I'm seeing similar issues as Vue when I run the e2e tests – typing into the `Confirmation Code` field doesn't seem to work:
Screen Shot 2021-11-02 at 1 50 28 PM
Screen Shot 2021-11-02 at 2 02 23 PM

**Comment by wlee221** [comment]
@ericclemmons Ah, I think I know what the problem is!

1. you should preferably use

```diff
- cy.findByLabelText('Confirmation Code').type('invalidcode');
+ cy.findInputField('Confirmation Code').type('invalidcode');
```
which searches for accessible textbox instead of the label.

2. In Vue and Angular, code field has `type="number"`, so `dom-testing-library` thinks it's a spinbutton instead of a textbox.

I think we should make `type` consistent first, then we can figure out the tests.

**Comment by ericclemmons** [comment]
@wlee221 I attempted that change locally, but it didn't seem to resolve it.  I agree, the `type` should be consistent and as a `text`. (Though it's a number, the spin controls don't help because they're not incrementing like a quantity)

**Review by wlee221 — APPROVED** [review]

**Pull request merged**
