### PR TITLE
Complete E2E Test Coverage

### PR DESCRIPTION
**Pull request by ericclemmons**
*Description of changes:*

The goal of this PR is to identify what tests were skipped & failing so that we can complete support.

- [x] Remove all `@todo-*` tags from `.feature` files
- [x] Resolve Angular failures
- [x] Resolve React failures
- [x] Resolve Vue failures

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ericclemmons** [comment]
@wlee221 The only failure I'm seeing is from my _new_ `i18n.feature`.  What I should do here is combine `auth-with-translations` and these together, as we discussed. But giving preference to _your_ test, but using the `i18n` name to match the docs.

**Comment by wlee221** [comment]
@ericclemmons, that sounds good to me!

**Comment by ericclemmons** [comment]
@wlee221 All `@todo-*` tests should be as they've been promoted to `@angular|@react|@vue` (and are ran in CI + `main`)

Is that what you meant?

**Comment by wlee221** [comment]
You're totally right, scratch what I said xD

**Comment by ErikCH** [comment]
The Vue tests should pass now. We'll see when they run again

**Comment by ericclemmons** [comment]
@ErikCH It looks like the Vue test is failing because `Email` isn't being translated:

```json
Email: 'メールアドレス',
```

Screen Shot 2021-09-28 at 12 19 34 PM

**Comment by ericclemmons** [comment]
For example, here's the fixed React version:
> Screen Shot 2021-09-28 at 12 21 11 PM

**Comment by wlee221** [comment]
Just pushed an angular commit, I could confirm that `i18n` test runs locally.
Screen Shot 2021-09-28 at 11 10 19 AM
.

**Comment by wlee221** [comment]
Ugh, looking over angular test now.

**Comment by wlee221** [comment]
Let's gooooo 🚢

**Review by wlee221 — APPROVED** [review]

**Review by eddiekeller — APPROVED** [review]
Nice job!

**Pull request merged**
