### PR TITLE
Add dutch translation

### PR DESCRIPTION
**Pull request by rvmourik**
*Description of changes:*
I added Dutch translations through the dictionaries.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by wlee221 — CHANGES_REQUESTED** [review]
Looks good! Can you update our [i18n docs](https://ui.docs.amplify.aws/components/authenticator#internationalization-i18n) to mention Dutch support as well?

The file is located at https://github.com/aws-amplify/amplify-ui/blob/main/docs/src/pages/components/authenticator/index.page.mdx, on lines 377-390.

Languages (below English) are listed there alphabetically according to their full language name.

**Comment by rvmourik** [comment]
> Looks good! Can you update our [i18n docs](https://ui.docs.amplify.aws/components/authenticator#internationalization-i18n) to mention Dutch support as well?
> 
> The file is located at https://github.com/aws-amplify/amplify-ui/blob/main/docs/src/pages/components/authenticator/index.page.mdx, on lines 377-390.
> 
> Languages (below English) are listed there alphabetically according to their full language name.

Hi @wlee221,

Sure thing, I've added another commit for that just now.

**Comment by reesscot** [comment]
Hi @rvmourik, thanks for updating your PR with the i18n. Can you please merge main into your branch so that the PR Preview will build?

**Comment by rvmourik** [comment]
@reesscot Done!

**Review by reesscot — APPROVED** [review]
LGTM, thank you for your contribution!

**Pull request merged**
