### PR TITLE
fix: update link

### PR DESCRIPTION
**Pull request by 0618**
#### Description of changes

Update link caught by link-checker https://github.com/aws-amplify/amplify-ui/actions/runs/5124356237/jobs/9216447982?pr=3986

#### Checklist

- [x] Have read the [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md)
- [ ] PR description included
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] `yarn test` passes and tests are updated/added
- [ ] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by calebpollman — COMMENTED** [review]
I'm not having issues with the old URL but am seeing a redirect when i navigate to it. Does the link checker fail on redirects?

**Review by sreeramsama — APPROVED** [review]

**Comment by 0618** [comment]
> I'm not having issues with the old URL but am seeing a redirect when i navigate to it. Does the link checker fail on redirects?

Yes, we fail on those redirected links so that we can keep our links up-to-date

**Comment by calebpollman** [comment]
> > I'm not having issues with the old URL but am seeing a redirect when i navigate to it. Does the link checker fail on redirects?
> 
> Yes, we fail on those redirected links so that we can keep our links up-to-date

But if the redirect works we should be good? Not sure if we really need to block our pipeline if there is ultimately a working link still

**Comment by 0618** [comment]
> But if the redirect works we should be good? Not sure if we really need to block our pipeline if there is ultimately a working link still

Redirected links are usually outdated links. We fail on those because we'd like to use fresh links. 

If it's to tedious to update 1 or 2 out-dated links, we can accumulate to, say, 5 redirected links before failing.

What do you think?

**Comment by calebpollman** [comment]
> > But if the redirect works we should be good? Not sure if we really need to block our pipeline if there is ultimately a working link still
> 
> Redirected links are usually outdated links. We fail on those because we'd like to use fresh links.
> 
> If it's to tedious to update 1 or 2 out-dated links, we can accumulate to, say, 5 redirected links before failing.
> 
> What do you think?

MSTM

**Pull request merged**
