### PR TITLE
fix(ci): fix build test steps to be jobs instead of steps

### PR DESCRIPTION
**Pull request by thaddmt**
#### Checklist

- [ ] Have read the [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md)
- [ ] PR description included
- [ ] `yarn test` passes and tests are updated/added
- [ ] PR title and commit messages follow [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) syntax
- [ ] _If this change should result in a version bump_, [changeset added](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) (This can be done after creating the PR.) This does not apply to changes made to `docs`, `e2e`, `examples`, or other private packages.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by thaddmt** [comment]
Verified this seems to correctly run the checks - https://github.com/aws-amplify/amplify-ui/actions/runs/10692158848

**Review by jordanvn — APPROVED** [review]
Looks good to me! Good to know that workflows can't be ran as steps

**Review by timngyn — APPROVED** [review]

**Review by calebpollman — COMMENTED** [review]
@esauerbo Can you please take a look here and verify that we didn't merge anything problematic?

**Comment by esauerbo** [comment]
> @esauerbo Can you please take a look here and verify that we didn't merge anything problematic?

Yup LGTM

**Pull request merged**
