### PR TITLE
feat(geo): Geo component end to end tests

### PR DESCRIPTION
**Pull request by slaymance**
#### Description of changes

This Pull Request adds the end to end tests for `AmplifyMap` and `Geocoder` components to our feature branch (`feat-geo`) which will be merged to `main` on the date of the scheduled GA release for Geo components.

This pull request is part of a series:
- https://github.com/aws-amplify/amplify-ui/pull/1570
- https://github.com/aws-amplify/amplify-ui/pull/1571
- https://github.com/aws-amplify/amplify-ui/pull/1573
- https://github.com/aws-amplify/amplify-ui/pull/1574

#### How to validate tests
1. Pull our geo tag branch which contains all components and tests
```shell
git fetch origin && git checkout ui-geo/main
```
2. Pull the map test environment
```shell
cd environments/basic-map && yarn pull && cd -
```
3. Setup the package
```shell
yarn setup
```
4. Start a development instance of the example apps
```shell
yarn next-example dev
```
5. In a new terminal window, run the geo e2e tests and verify they pass
```shell
yarn e2e test:geo -e "TAGS=@react and not @skip"
``` 

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are updated
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by slaymance** [comment]
Failed checks are expected here, we will ensure CI passes before merging the `feat-geo` branch to `main`.

**Comment by slaymance** [comment]
The main code to review in this PR is the `examples/` and `packages/e2e/` changes. `environments/` is mostly just the boilerplate generated by the CLI.

**Review by reesscot — APPROVED** [review]
LGTM

**Review by jacoblogan — APPROVED** [review]
LGTM

**Pull request merged**
