### PR TITLE
chore(ui-react): Replace lodash utils that check emptiness

### PR DESCRIPTION
**Pull request by ioanabrooks**
#### Description of changes

Functions replaced:

* isNil 
* isEmpty
* includes - replaced with Array.includes
* has
* isMap
* isSet

Additionally `isEmptyObject`, `isEmptyArray`, `areEmptyObjects`, `areEmptyArrays` utils are moved from react-core pkg to ui pkg.

Unit tests are added.

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are updated
- [ ] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by calebpollman — COMMENTED** [review]
LGTM, can we just fix the codeQL warning in _[packages/ui/src/helpers/authenticator/context.ts](https://github.com/aws-amplify/amplify-ui/pull/3376/files#diff-2d68fae823bcc41816da2e2f664acadba4757d37c40a0b462a42544b03147314)_

**Comment by ioanabrooks** [comment]
> LGTM, can we just fix the codeQL warning in _[packages/ui/src/helpers/authenticator/context.ts](https://github.com/aws-amplify/amplify-ui/pull/3376/files#diff-2d68fae823bcc41816da2e2f664acadba4757d37c40a0b462a42544b03147314)_

Done! looks like I ended up with a few artifacts post merge conflict resolution, thanks for catching!

**Review by calebpollman — APPROVED** [review]
Thanks @ioanabrooks 🚢

**Review by dbanksdesign — APPROVED** [review]
Great work!

**Pull request merged**
