### PR TITLE
chore(docs): add flutter auth dev preview

### PR DESCRIPTION
**Pull request by Jordan-Nelson**
#### Description of changes
- Update amplify flutter versions to include latest stable and dev-preview releases
- Add web and desktop example to docs for amplify flutter

Updated Example:

Screen Shot 2022-08-04 at 2 12 59 PM

#### Description of how you validated changes

The changes have been deployed here: https://chore-auth-v-next.d1m6l3c1y80m52.amplifyapp.com/flutter/connected-components/authenticator

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are updated
- [ ] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by haverchuck — DISMISSED** [review]

**Review by dnys1 — DISMISSED** [review]

**Review by 0618 — COMMENTED** [review]
The docs part LGTM

**Comment by reesscot** [comment]
Can we hide this page in the Flutter docs? https://chore-auth-v-next.d1m6l3c1y80m52.amplifyapp.com/flutter/connected-components/authenticator/headless

**Review by reesscot — APPROVED** [review]
Thanks for including the deployed test site. I did some smoke testing and it LGTM

**Review by hbuchel — APPROVED** [review]
LGTM

**Pull request merged**
