### PR TITLE
fix: 🐛 i18n typo

### PR DESCRIPTION
**Pull request by ThaddeusJiang**
#### Description of changes

`Enter your Username` is typo, it should be `Enter your username`.

CleanShot 2023-07-05 at 13 30 16@2x

#### Checklist

- [ ] Have read the [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md)
- [ ] PR description included
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] `yarn test` passes and tests are updated/added
- [ ] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by calebpollman** [comment]
Thank you for opening this @ThaddeusJiang! Can you please add a changeset to the PR?

**Comment by ThaddeusJiang** [comment]
> Thank you for opening this @ThaddeusJiang! Can you please add a changeset to the PR?

@calebpollman I have added a changeset, could you review it?

**Comment by reesscot** [comment]
Hi @ThaddeusJiang, 
Changing the capitalization of Username would be breaking changes for customers who have manually overwritten the misspelling in their applications. Instead of changing the capitalization, can you change your fix to ensure that all translations have a "Enter your Username" key in addition to the "Enter your username" key? That should also fix the issue.

**Comment by ThaddeusJiang** [comment]
> Hi @ThaddeusJiang, Changing the capitalization of Username would be breaking changes for customers who have manually overwritten the misspelling in their applications. Instead of changing the capitalization, can you change your fix to ensure that all translations have a "Enter your Username" key in addition to the "Enter your username" key? That should also fix the issue.

hi @reesscot 
Even the customer have overwritten the misspelling, the bug will be fixed automatically.
Could you confirm again?

**Pull request closed without merging**
