### PR TITLE
feat(Authenticator): Adding documentation for Swift

### PR DESCRIPTION
**Pull request by ruisebas**
#### Description of changes

This PR adds documentation for the Authenticator UI component for Swift

#### Checklist

- [x] Have read the [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md)
- [x] PR description included
- [x] Relevant documentation is changed or added (and PR referenced)
- [x] `yarn test` passes and tests are updated/added
- [ ] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by hdworld11 — APPROVED** [review]

**Comment by calebpollman** [comment]
@ruisebas Can you please read over our [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md) and acknowledge that you are aware of the publishing expectations?

**Comment by ruisebas** [comment]
@calebpollman checked!

Also, the *e2e / docs* build is failing due to:
```
❌ [RETURNING STATUS...] 404 for page #127 link #34 -- https://github.com/aws-amplify/amplify-ui-swift-authenticator from A tag "Amplify UI Swift - Authenticator" on  page ***/swift/connected-components/authenticator
```

This is because the [**amplify-ui-swift-authenticator**](https://github.com/aws-amplify/amplify-ui-swift-authenticator) repo is still private.

**Comment by thaddmt** [comment]
> @calebpollman checked!
> 
> Also, the _e2e / docs_ build is failing due to:
> 
> ```
> ❌ [RETURNING STATUS...] 404 for page #127 link #34 -- https://github.com/aws-amplify/amplify-ui-swift-authenticator from A tag "Amplify UI Swift - Authenticator" on  page ***/swift/connected-components/authenticator
> ```
> 
> This is because the [**amplify-ui-swift-authenticator**](https://github.com/aws-amplify/amplify-ui-swift-authenticator) repo is still private.

When is this planned to go public/launch?

**Comment by ruisebas** [comment]
> When is this planned to go public/launch?

On Monday (April 17)

**Comment by reesscot** [comment]
@ruisebas Can we remove the link for now?

**Comment by ruisebas** [comment]
@reesscot i've removed the link, the build is now successful 👍

**Review by hdworld11 — APPROVED** [review]

**Review by harsh62 — APPROVED** [review]

**Review by calebpollman — APPROVED** [review]

**Review by reesscot — APPROVED** [review]

**Pull request merged**
