### PR TITLE
chore: Update yarn.lock

### PR DESCRIPTION
**Pull request by joebuono**
#### Description of changes

The dependencies on the main branch are out of date. This PR updates the `yarn.lock` file by running the command `rm yarn.lock && yarn install`

#### Checklist

- [X] PR description included
- [X] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by wlee221** [comment]
Let's see if tests pass 😈

**Review by 0618 — APPROVED** [review]

**Review by slaymance — APPROVED** [review]
Welcome to the future, dependencies!

**Review by zchenwei — APPROVED** [review]

**Review by calebpollman — APPROVED** [review]
LGTM 🚢

**Review by wlee221 — APPROVED** [review]
Thanks @joebuono!

**Pull request merged**
