### PR TITLE
fix(docs): example.react-native src path for aws-exports

### PR DESCRIPTION
**Pull request by flexbox**
#### Description of changes

running `amplify pull` will output the file to a `src/` folder

image

#### Issue

--

#### Description of how you validated changes

Fix path when copy-pasting from
https://ui.docs.amplify.aws/react-native/connected-components/authenticator/configuration 

#### Checklist

- [x] Have read the [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md)
- [x] PR description included
- [x] Relevant documentation is changed or added (and PR referenced)
- [x] `yarn test` passes and tests are updated/added
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by calebpollman — APPROVED** [review]
LGTM

**Review by hbuchel — APPROVED** [review]

**Comment by calebpollman** [comment]
Thank you for the contribution @flexbox!

**Review by zchenwei — APPROVED** [review]

**Comment by calebpollman** [comment]
Merging without e2e tests running as the code change here is related to an example block that does not run.

**Comment by flexbox** [comment]
@offlineprogrammer sure Let's do it!

**Pull request merged**
