### PR TITLE
chore: add types field to exports

### PR DESCRIPTION
**Pull request by zchenwei**
#### Description of changes

We need to add `types` field to `exports` to help Typescript identify the types file. In newer Typescript versions which support conditional exports(`exports` field), it will error out when `types` field is missing though you have specified such a field at the top level of `package.json`.

Before:
Screenshot 2023-05-08 at 11 28 31 AM

After:
Screenshot 2023-05-08 at 11 31 39 AM

#### Checklist

- [x] Have read the [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md)
- [x] PR description included
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by 0618 — APPROVED** [review]

**Review by ioanabrooks — APPROVED** [review]

**Review by wlee221 — APPROVED** [review]

**Review by thaddmt — APPROVED** [review]
Do we. need to add this to any of our other packages?

**Comment by zchenwei** [comment]
> Do we. need to add this to any of our other packages?

It seems we did but we miss this particular one :(

**Comment by zchenwei** [comment]
> Do we. need to add this to any of our other packages?

It seems we did but we miss this particular one :(

**Review by reesscot — APPROVED** [review]

**Review by reesscot — APPROVED** [review]

**Review by wlee221 — APPROVED** [review]

**Review by 0618 — APPROVED** [review]
LGTM! Thanks for fixing it!

**Pull request merged**
